Merge build changes into new script and rebuild
git-svn-id: https://ns2/svnsrc/buildscripts/trunk@3670 a03fbada-158d-47ef-9f12-77e997805b15

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 SVNIP=192.168.25.1
-SVNBASE=http://${SVNIP}/svn 
+SVNBASE=http://${SVNIP}/svn
 
 #Setup layout path
 SRCDIR=/usr/src
@@ -17,6 +17,7 @@ PKGBUILDDIR=${DISTDIR}/build
 ARCHROOT=/build
 SVNURL=${SVNBASE}/distro/
 SVNUPDATE=0;
+AMDEF="1.11";
 
 #Multiarch Definitions
 MARCH_x86_64="x86_32|i[3-6]86|x86_64"
@@ -187,6 +188,13 @@ svn_load_pkg() {
   fi;
   if [ ! -d ${SRCDIR}/${PKGSVNDIR} ];then
     svn co ${SVNURL}/${PKGSVNDIR} ${SRCDIR}/${PKGSVNDIR} || return 1
+    #some packages are retards null config them
+    if [ -e ${SRCDIR}/${PKGSVNDIR}/configure ];then
+      (cd ${SRCDIR}/${PKGSVNDIR}
+       sh ./configure;
+       svn up
+       make distclean)
+    fi;
    elif [ "${SVNUPDATE}" == "1" ];then
     svn up ${SRCDIR}/${PKGSVNDIR}
   fi;
@@ -351,12 +359,12 @@ make_cc_destdir() {
   if [ "${NOMAKEFLAGS}" == "1" ];then
     unset CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
     /usr/bin/make ${MAKE_J} V=1 AR=${AR} RANLIB=${RANLIB} LD="${LD}" SYSROOT=${SYSROOT} \
-      CXX="${CXX} ${CC_SYSROOT}" CC="${CC} $CC_SYSROOT}" DESTDIR=${DIST_ROOT} ${MAKEOPTS} \
+      CXX="${CXX} ${CC_SYSROOT}" CC="${CC} $CC_SYSROOT}" ${MAKEOPTS} \
       ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS}
     RES=$?
     if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
       /usr/bin/make V=1 AR=${AR} RANLIB=${RANLIB} LD="${LD}" SYSROOT=${SYSROOT} \
-        CXX="${CXX} ${CC_SYSROOT}" CC="${CC} $CC_SYSROOT}" DESTDIR=${DIST_ROOT} ${MAKEOPTS} \
+        CXX="${CXX} ${CC_SYSROOT}" CC="${CC} $CC_SYSROOT}" ${MAKEOPTS} \
         ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
      elif [ ${RES} != 0 ];then
       return 1
@@ -364,12 +372,13 @@ make_cc_destdir() {
     /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install
    else
     /usr/bin/make ${MAKE_J} V=1 LDFLAGS="${LDFLAGS}" CFLAGS="${CFLAGS}" AR=${AR} RANLIB=${RANLIB} LD="${LD}" \
-      CXX="${CXX} ${CC_SYSROOT}" CC="${CC} ${CC_SYSROOT}" DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} && \
-      /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install
+      CXX="${CXX} ${CC_SYSROOT}" CC="${CC} ${CC_SYSROOT}" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
+      /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install || return 1
     RES=$?
     if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
       /usr/bin/make V=1 LDFLAGS="${LDFLAGS}" CFLAGS="${CFLAGS}" AR=${AR} RANLIB=${RANLIB} LD="${LD}" \
-        CXX="${CXX} ${CC_SYSROOT}" CC="${CC} ${CC_SYSROOT}" DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} install ${MAKETARGETS} || return 1
+        CXX="${CXX} ${CC_SYSROOT}" CC="${CC} ${CC_SYSROOT}" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
+      /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install || return 1
      elif [ ${RES} != 0 ];then
       return 1
     fi;
@@ -389,8 +398,10 @@ imake_cross_build() {
 
   sysroot_fixup ${1}
 
-  /usr/bin/make V=1 CXX="${CXX} ${CC_SYSROOT}" CC="${CC_TMP} ${CC_SYSROOT}" SHLIBDIR=/usr/X11R7/${B_LIBDIRS} DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} install \
-       LOCAL_LDFLAGS="-L${SYSROOT}/usr/X11R7/${B_LIBDIRS}" || return 1
+  /usr/bin/make V=1 CXX="${CXX} ${CC_SYSROOT}" CC="${CC_TMP} ${CC_SYSROOT}" SHLIBDIR=/usr/X11R7/${B_LIBDIRS} \
+       LOCAL_LDFLAGS="-L${SYSROOT}/usr/X11R7/${B_LIBDIRS}" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
+  /usr/bin/make V=1 CXX="${CXX} ${CC_SYSROOT}" CC="${CC_TMP} ${CC_SYSROOT}" SHLIBDIR=/usr/X11R7/${B_LIBDIRS} \
+       LOCAL_LDFLAGS="-L${SYSROOT}/usr/X11R7/${B_LIBDIRS}" ${MAKEOPTS} ${ARCHMOPT} DESTDIR=${DIST_ROOT} || return 1
 }
 
 cmake_cross_build() {
@@ -425,11 +436,12 @@ cmake_cross_build() {
     sh ${SRCDIR}/${PSOURCEDIR}/.build-info/post-config ${2} ${SRCDIR}/${PSOURCEDIR} ${DIST_ROOT}
   fi;
 
-  /usr/bin/make ${MAKE_J} V=1 DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} && \
+  /usr/bin/make ${MAKE_J} V=1 ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} && \
     /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install
   RES=$?
   if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
-    /usr/bin/make V=1 DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} install || return 1
+    /usr/bin/make V=1 ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
+    /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install || return 1
    elif [ ${RES} != 0 ];then
      return 1
   fi;
@@ -536,12 +548,15 @@ autoconf_cross_build() {
         return 1
       fi;
      else
-      /usr/bin/make ${MAKE_J} DESTDIR=${DIST_ROOT} LD="${LD}" CC="${CC}" CXX="${CXX}" HOSTCC="${BUILD}-gcc" HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} && \
-        /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install
+      /usr/bin/make ${MAKE_J} LD="${LD}" CC="${CC}" CXX="${CXX}" HOSTCC="${BUILD}-gcc" \
+        HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} \
+        ${MAKEALL} ${MAKETARGETS} && \
+      /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install
       RES=$?
       if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
-        /usr/bin/make DESTDIR=${DIST_ROOT} LD="${LD}" CC="${CC}" CXX="${CXX}" HOSTCC="${BUILD}-gcc" HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} install || return 1
-        /usr/bin/make  LD="${LD}" CC="${CC}" CXX="${CXX}" HOSTCC="${BUILD}-gcc" HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} &&\
+        /usr/bin/make LD="${LD}" CC="${CC}" CXX="${CXX}" HOSTCC="${BUILD}-gcc" \
+          HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} \
+          ${MAKEALL} ${MAKETARGETS} || return 1
         /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install || return 1
        elif [ ${RES} != 0 ];then
         return 1
@@ -575,6 +590,16 @@ build_project() {
   AVER=VERSION_${1}
   VERSION=${!AVER-$VERSION}
 
+  #For null config i need this set up early
+  if [ "${AMVER}" ];then
+    ACLOCAL=aclocal-${AMVER}
+    AUTOMAKE=automake-${AMVER}
+   else
+    ACLOCAL=aclocal-${AMDEF}
+    AUTOMAKE=automake-${AMDEF}
+  fi;
+  export ACLOCAL AUTOMAKE
+	
   svn_load_pkg ${PROJECT} ${PROJECT}${VERSEP}${VERSION}
 
   if [ "${VERSION}" ];then
@@ -1370,20 +1395,19 @@ build_toolchain() {
   #Base dependancies
   (build_packages ${1} libtool make gperf gettext sed ncursesw ncurses texinfo zlib binutils libsigsegv gawk m4 \
                        bison diffutils flex attr acl pcre libsepol libselinux file \
-                       libcap coreutils readline bash popt rsync) || return 1
+                       libcap coreutils readline bash intltool popt rsync) || return 1
 
   #Base programs
-  (build_packages ${1} xz libxml2 libxslt gnome-doc-utils scrollkeeper gtk-doc expat Python libffi glib pkg-config docbook-4.1.2 \
-            docbook-4.2  docbook-4.3 docbook-4.4  docbook-4.5 docbook-xsl nettle p11-kit gnutls libgpg-error libgcrypt \
-            libassuan libksba pth gnupg openssl trousers libprelude libtirpc Linux-PAM slang gobject-introspection \
-            vala pixman libidn wget which) || return 1
-
+  (build_packages ${1} xz libxml2 p11-kit nettle gnutls libgpg-error libgcrypt libxslt gnome-doc-utils scrollkeeper \
+            gtk-doc expat Python libffi glib pkg-config docbook-4.1.2 docbook-4.2  docbook-4.3 \
+            docbook-4.4  docbook-4.5 docbook-xsl libassuan libksba pth libusb libusb-compat gnupg openssl trousers \
+            libprelude libtirpc Linux-PAM slang gobject-introspection vala pixman gengetopt libidn wget which) || return 1
   
   if [ ! -e ${STATDIR}/${1}/done/util-linux ];then
     rm /usr/lib64/libblkid.a /usr/lib64/libuuid.a /usr/lib64/libblkid.la /usr/lib64/libuuid.la >/dev/null 2>&1
   fi;
 
- (build_packages ${1} util-linux flex sed nano rsync grep less gzip tar pkg-config cpio iana-etc) || return 1
+ (build_packages ${1} util-linux nano rsync grep less gzip tar pkg-config cpio iana-etc) || return 1
 
   #Add required perl modules from cpan
   for pmod in XML::Parser XML::SAX Font::TTF;do
@@ -1392,25 +1416,37 @@ build_toolchain() {
     fi;
   done
 
- (build_packages ${1} xmlto xmltoman giflib freetype fontconfig fontforge fonttools jpeg openjpeg libpng libmng OpenSP \
-                      openjade ) || return 1
+ (build_packages ${1} xmlto xmltoman giflib freetype fontconfig fontforge fonttools jpeg libpng openjpeg libmng OpenSP \
+                      openjade c-ares curl git) || return 1
 
- #This will fail due to Mesa so dont bail only do it on first pass
- if [ ! -e ${STATDIR}/${1}/fail/Xorg ];then
-   (build_packages ${1} Xorg) || touch ${STATDIR}/${1}/fail/Xorg
- fi;
- (build_packages ${1} libdrm llvm Mesa glu glw freeglut intltool libverto krb5 cups dbus systemd pcsc-lite mtdev Xorg) || return 1
- (build_packages ${1} tiff atk cairo pango gdk-pixbuf gtk+) || return 1 
- (build_packages ${1} patch alsa-lib icedtea6 lcms2 icedtea7) || return 1
+  #This will fail due to Mesa so dont bail only do it on first pass
+  if [ ! -e ${STATDIR}/${1}/fail/Xorg ];then
+    (build_packages ${1} Xorg) || touch ${STATDIR}/${1}/fail/Xorg
+  fi;
 
- (build_packages ${1} libusb libusb-compat cmake yasm nasm kmod module-init-tools fuse swig keyutils neon) || return 1
- (build_packages ${1} libunistring txt2man printproto portablexdr ppp libIDL ORBit2 dbus-glib GConf libbonobo) || return 1
- (build_packages ${1} gc guile libmad Xaw3d gv polkit polkit-gnome gengetopt libidn c-ares curl rtmpdump apr \
-                      apr-iconv sqlite-autoconf M2Crypto libnl-1 libnl crda) || return 1
+  (build_packages ${1} cairo pango libdrm llvm intltool krb5 cups dbus kmod module-init-tools cryptsetup systemd \
+                       Mesa glu glw mtdev Xorg freeglut mtdev) || return 1
 
- (build_packages ${1} apache-ant tcl8 tk8 db unixODBC cyrus-sasl openslp openldap mysql postgresql) ||return 1
- (build_packages ${1} apr-util httpd subversion) ||return 1
- (build_packages ${1} qt-4) || return 1
+  (build_packages ${1} cairo pango libdrm llvm intltool cmake talloc tevent libverto krb5 cups dbus kmod module-init-tools \
+                       cryptsetup systemd Mesa glu glw mtdev Xorg freeglut pcsc-lite) || return 1
+
+  (build_packages ${1} tiff atk gdk-pixbuf gtk+) || return 1 
+
+  (build_packages ${1} patch alsa-lib fastjar icedtea6 lcms2 icedtea7) || return 1
+  (build_packages ${1} tcl8 tk8 db unixODBC cyrus-sasl openslp openldap mysql postgresql) ||return 1
+  (build_packages ${1} apr apr-iconv apr-util httpd sqlite-autoconf swig keyutils neon subversion) || return 1
+  (build_packages ${1} qt-4) || return 1
+
+  (build_packages ${1} libusb libusb-compat yasm nasm kmod module-init-tools fuse swig keyutils neon) || return 1
+  (build_packages ${1} libunistring txt2man printproto portablexdr ppp libIDL ORBit2 dbus-glib GConf libbonobo) || return 1
+  (build_packages ${1} gc guile libmad Xaw3d gv polkit polkit-gnome rtmpdump) || return 1
+
+  (build_packages ${1} gc guile libmad Xaw3d gv polkit polkit-gnome rtmpdump
+                       apr apr-iconv sqlite-autoconf M2Crypto libnl-1 libnl crda) || return 1
+
+  (build_packages ${1} apache-ant tcl8 tk8 db unixODBC cyrus-sasl openslp openldap mysql postgresql) ||return 1
+  (build_packages ${1} apr-util httpd subversion) ||return 1
+  (build_packages ${1} qt-4) || return 1
 
   #Time to build a static gcc bootstrap distributable
   (build_gcc_bootstrap ${1} ${2} ${1} static) || return 1
